#!/usr/bin/env bash

command -v xmllint >/dev/null 2>&1 || { echo >&2 "I require xmllint but it's not installed.  Aborting. (for ubuntu: sudo apt-get install libxml2-utils )"; exit 1; }

ART_ID=`xmllint --xpath "/*[local-name()='project']/*[local-name()='artifactId']/text()" pom.xml`
TAG=`xmllint --xpath "/*[local-name()='project']/*[local-name()='version']/text()" pom.xml`


DOC_TAG="afrozaar/$ART_ID:$TAG"
DOCKER_REGISTRY=`xmllint --xpath "/*[local-name()='project']/*[local-name()='properties']/*[local-name()='docker.registry']/text()" pom.xml`
CONTAINER_PORT=`xmllint --xpath "/*[local-name()='project']/*[local-name()='properties']/*[local-name()='container.port']/text()" pom.xml`
AWS_TAG="$DOCKER_REGISTRY/$DOC_TAG"

echo "{
  \"AWSEBDockerrunVersion\": \"1\",
  \"Image\": {
    \"Name\": \"${AWS_TAG}\",
    \"Update\": \"true\"
  },
  \"Ports\": [
    {
      \"ContainerPort\": \"${CONTAINER_PORT}\"
    }
  ],
  \"Logging\": \"/var/log/nginx\"
}" | tee Dockerrun.aws.json
